// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: testPackage.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - TestPackageRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface TestPackageRoot : GPBRootObject
@end

#pragma mark - KFATestMessage

typedef GPB_ENUM(KFATestMessage_FieldNumber) {
  KFATestMessage_FieldNumber_Name = 1,
  KFATestMessage_FieldNumber_Sex = 2,
  KFATestMessage_FieldNumber_Age = 3,
};

@interface KFATestMessage : GPBMessage

/** 姓名 必须 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;
/** Test to see if @c name has been set. */
@property(nonatomic, readwrite) BOOL hasName;

/** 性别 必须 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sex;
/** Test to see if @c sex has been set. */
@property(nonatomic, readwrite) BOOL hasSex;

/** 年龄 可选 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *age;
/** Test to see if @c age has been set. */
@property(nonatomic, readwrite) BOOL hasAge;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
